config/routes.rb
Rads::Application.routes.draw do
  get "record_provenance/show"
  resources :audited_activities, only: [:index, :show]

  resources :project_users, except: [:new, :create, :edit]

  resources :projects, except: [:destroy] do
    resources :project_memberships, except: [:edit, :update]
    resources :project_affiliated_records, except: [:edit, :update]
  end

  resources :core_users, except: [:new, :create, :edit]
  resources :cores, except: [:edit, :update, :destroy] do
    resources :core_memberships, except: [:edit, :update]
  end

  resources :records, only: [:index, :show, :new, :create, :destroy]
  resources :repository_users

  get "switch_user/switch_to", as: 'switch_to'
  get "switch_user/destroy", as: 'switch_back'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/check"
  root 'sessions#new'

  

end

app/models/core.rb
class Core < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  has_many :core_memberships, inverse_of: :core
  has_one :core_user, inverse_of: :core

  validates_presence_of :name
  validates_presence_of :creator_id

  def to_s
    name
  end

  def is_member?(repository_user)
    core_memberships.where(repository_user_id: repository_user.id).exists?
  end
end

app/controllers/cores_controller.rb
class CoresController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @core.creator_id = current_user.id
    @core.core_memberships.build( repository_user_id: current_user.id )
    @core.build_core_user(name: "Core #{ @core.name } User", is_enabled: true)
    respond_to do |format|
      if @core.save
        format.html { redirect_to @core, notice: 'Core was successfully created.' }
        format.json { render action: 'show', status: :created, location: @core }
      else
        format.html { render action: 'new' }
        format.json { render json: @core.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @core.update(core_params)
        format.html { redirect_to @core, notice: 'Core was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @core.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def core_params
      params.require(:core).permit(:name, :description)
    end
end

app/helpers/cores_helper.rb
module CoresHelper
end

app/views/cores/_form.html.erb
<%= form_for(@core) do |f| %>
  <% if @core.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@core.errors.count, "error") %> prohibited this core from being saved:</h2>

      <ul>
      <% @core.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cores/edit.html.erb
<h1>Editing core</h1>

<%= render 'form' %>

<%= link_to 'Show', @core %> |
<%= link_to 'Back', cores_path %>

app/views/cores/index.html.erb
<h1>Listing cores</h1>

<% if @cores.empty? %>
<p>There are no cores to display.</p>
<% else %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Creator</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cores.each do |core| %>
      <tr>
        <td><%= core.name %></td>
        <td><%= core.description %></td>
        <td><%= core.creator %></td>
        <td><%= link_to 'Manage Memberships', core_core_memberships_path(core) if can? :create, CoreMembership.new(core_id: core.id) %></td>
        <td><%= link_to 'Show', core if can? :show, core%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<%= link_to 'New Core', new_core_path %>

app/views/cores/new.html.erb
<h1>New core</h1>

<%= render 'form' %>

<%= link_to 'Back', cores_path %>

app/views/cores/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @core.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @core.description %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @core.creator %>
</p>
<p>
  <strong>Core Members:</strong>
<%= render partial: 'core_memberships/core_memberships', locals: { core_memberships: @core.core_memberships } %>
<%= link_to 'Add New Member', new_core_core_membership_path(@core) if can? :create, CoreMembership.new(core_id: @core.id) %>
</p>
<%= link_to 'Back', cores_path %>