config/routes.rb
Rads::Application.routes.draw do
  get "record_provenance/show"
  resources :audited_activities, only: [:index, :show]

  resources :project_users, except: [:new, :create, :edit]

  resources :projects, except: [:destroy] do
    resources :project_memberships, except: [:edit, :update]
    resources :project_affiliated_records, except: [:edit, :update]
  end

  resources :core_users, except: [:new, :create, :edit]
  resources :cores, except: [:edit, :update, :destroy] do
    resources :core_memberships, except: [:edit, :update]
  end

  resources :records, only: [:index, :show, :new, :create, :destroy]
  resources :repository_users

  get "switch_user/switch_to", as: 'switch_to'
  get "switch_user/destroy", as: 'switch_back'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/check"
  root 'sessions#new'

  

end

app/models/project_affiliated_record.rb
class ProjectAffiliatedRecord < ActiveRecord::Base
  belongs_to :project
  belongs_to :affiliated_record, class_name: 'Record', foreign_key: 'record_id'
  validates_presence_of :project
  validates_presence_of :affiliated_record

  def to_s
    affiliated_record.to_s
  end
end

app/controllers/project_affiliated_records_controller.rb
class ProjectAffiliatedRecordsController < ApplicationController
  load_resource :project
  load_and_authorize_resource :project_affiliated_record, through: :project

  def index
  end

  def show
  end

  def new
    @unaffiliated_records = current_user.records.reject {|r| @project.is_affiliated_record? r}
  end

  def edit
  end

  def create
    @unaffiliated_records = current_user.records.reject {|r| @project.is_affiliated_record? r}
    respond_to do |format|
      if @project_affiliated_record.save
        format.html { redirect_to @project, notice: 'Project affiliated record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project_affiliated_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @project_affiliated_record.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project_affiliated_record.update(project_affiliated_record_params)
        format.html { redirect_to @project, notice: 'Project affiliated record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project_affiliated_record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project_affiliated_record.destroy
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_affiliated_record_params
      params.require(:project_affiliated_record).permit(:record_id)
    end
end

app/helpers/project_affiliated_records_helper.rb
module ProjectAffiliatedRecordsHelper
end

app/views/project_affiliated_records/_form.html.erb
<%= form_for [@project, @project_affiliated_record] do |f| %>
  <% if @project_affiliated_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_affiliated_record.errors.count, "error") %> prohibited this project_affiliated_record from being saved:</h2>

      <ul>
      <% @project_affiliated_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :record_id %><br>
    <%= f.collection_select(:record_id, @unaffiliated_records, :id, :to_s) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_affiliated_records/index.html.erb
<h1>Listing affiliated records</h1>

<% if @project_affiliated_records.empty? %>
<p>There are no affiliated records to display.</p>
<% else %>
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Record</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_affiliated_records.each do |project_affiliated_record| %>
      <tr>
        <td>
          <%= link_to project_affiliated_record.project, project_path(project_affiliated_record.project.id) %>
        </td>
        <td>
          <%= link_to project_affiliated_record.affiliated_record, record_path(project_affiliated_record.affiliated_record.id) %>
        </td>
        <td><%= link_to 'Show', [project_affiliated_record.project, project_affiliated_record] %></td>
        <td><%= link_to 'Destroy', [project_affiliated_record.project, project_affiliated_record], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<%= link_to 'New Project affiliated record', new_project_project_affiliated_record_path(@project) %>

app/views/project_affiliated_records/new.html.erb
<h1>Affiliate Record to <%= @project %></h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>

app/views/project_affiliated_records/show.html.erb
<p>
  <strong>Project:</strong>
  <%= link_to @project_affiliated_record.project, project_path(@project_affiliated_record.project.id) %>
</p>

<p>
  <strong>Record:</strong>
  <%= link_to @project_affiliated_record.affiliated_record, record_path(@project_affiliated_record.affiliated_record.id) %>
</p>

<%= link_to 'Back', @project %>