config/routes.rb
Rads::Application.routes.draw do
  get "record_provenance/show"
  resources :audited_activities, only: [:index, :show]

  resources :project_users, except: [:new, :create, :edit]

  resources :projects, except: [:destroy] do
    resources :project_memberships, except: [:edit, :update]
    resources :project_affiliated_records, except: [:edit, :update]
  end

  resources :core_users, except: [:new, :create, :edit]
  resources :cores, except: [:edit, :update, :destroy] do
    resources :core_memberships, except: [:edit, :update]
  end

  resources :records, only: [:index, :show, :new, :create, :destroy]
  resources :repository_users

  get "switch_user/switch_to", as: 'switch_to'
  get "switch_user/destroy", as: 'switch_back'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/check"
  root 'sessions#new'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  validates_presence_of :name
  validates_presence_of :creator_id
  has_many :project_memberships, inverse_of: :project
  has_one :project_user, inverse_of: :project
  has_many :project_affiliated_records, inverse_of: :project
  has_many :records, through: :project_affiliated_records, source: :affiliated_record
  accepts_nested_attributes_for :project_affiliated_records, allow_destroy: true
  accepts_nested_attributes_for :project_memberships, allow_destroy: true

  def to_s
    name
  end

  def is_member?(user)
    project_memberships.where(user_id: user.id).exists?
  end

  def is_affiliated_record?(record)
    project_affiliated_records.where(record_id: record.id).exists?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
    @project_affiliated_records = @project.project_affiliated_records
    @project_memberships = @project.project_memberships
  end

  def new
    @unaffiliated_records = current_user.records
    @unaffiliated_records.each do |record|
      @project.project_affiliated_records.build(record_id: record.id)
    end

    @potential_members = User.all - [current_user]
    @potential_members.each do |user|
      @project.project_memberships.build(user_id: user.id)
    end
  end

  def edit
    @unaffiliated_records = current_user.records.reject {|r| @project.is_affiliated_record? r}
    @unaffiliated_records.each do |record|
      @project.project_affiliated_records.build(record_id: record.id)
    end

    @potential_members = User.all.reject {|u| @project.is_member? u}
    @potential_members.each do |user|
      @project.project_memberships.build(user_id: user.id)
    end
  end

  def create
    @project.creator_id = current_user.id
    @project.project_memberships.build( user_id: current_user.id )
    @project.build_project_user(name: "Project #{ @project.name } User", is_enabled: true)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      permitted_params = [
        project_affiliated_records_attributes: [:id, :_destroy, :record_id],
        project_memberships_attributes: [:id, :_destroy, :user_id]
      ]
      if current_user.type == 'RepositoryUser'
        permitted_params = [:name, :description] + permitted_params
      end
      params.require(:project).permit(permitted_params)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= render(partial: 'project_memberships_fieldset', locals: {f: f}) unless @potential_members.empty? %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_affiliated_records_fieldset.html.erb
  <fieldset>
    <%= f.fields_for :project_affiliated_records do |rf| %>
      <%= rf.hidden_field :id %>
      <%= rf.hidden_field :record_id %>
      <%= rf.check_box :_destroy, {:checked => rf.object.persisted?}, '0', '1' %>
      <%= rf.label :_destroy, rf.object.affiliated_record %>
      <br>
    <% end %>
  </fieldset>

app/views/projects/_project_memberships_fieldset.html.erb
  <fieldset>
    <legend>Project memberships</legend>
    <%= f.fields_for :project_memberships do |uf| %>
    <% if !uf.object.persisted? || can?(:destroy, uf.object) %>
      <%= uf.hidden_field :id %>
      <%= uf.hidden_field :user_id %>
      <%= uf.check_box :_destroy, {:checked => uf.object.persisted?}, '0', '1' %>
      <%= uf.label :_destroy, uf.object.user %>
      <br>
    <% end %>
    <% end %>
  </fieldset>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Creator</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.creator %></td>
        <td><%= link_to 'Show', project if can? :show, project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) if can? :edit, project %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path if can? :new, Project %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @project.creator %>
</p>

<% if can? :index, ProjectMembership.new(project_id: @project.id) %>
<% if @project_memberships.empty? %>
<p>This project has no members.</p>
<% else %>
<table>
  <thead>
    <tr>
      <th>Members</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_memberships.each do |project_membership| %>
      <tr>
        <td><%= project_membership.user %></td>
        <td><%= link_to 'Revoke', [project_membership.project, project_membership], method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, project_membership %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<% end %>

<%= link_to 'Add new member', new_project_project_membership_path(@project) if can? :new, ProjectMembership.new(project_id: @project.id) %>
<br>
<br>

<% if @project_affiliated_records.empty? %>
<p>There are no records affiliated with this project.</p>
<% else %>
<table>
  <thead>
    <tr>
      <th>Affiliated record</th>
      <th>Creator</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_affiliated_records.each do |project_affiliated_record| %>
      <tr>
        <td>
          <%= link_to project_affiliated_record, record_path(project_affiliated_record.record_id) %>
        </td>
        <td>
          <%= project_affiliated_record.affiliated_record.creator %>
        </td>
        <td><%= link_to 'Unaffiliate', [project_affiliated_record.project, project_affiliated_record], method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, project_affiliated_record %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= link_to 'Affiliate record', new_project_project_affiliated_record_path(@project) if can? :new, @project.project_affiliated_records.build() %>
<br>
<br>

<% if can? :edit, @project %>
<%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>