config/routes.rb
Rads::Application.routes.draw do
  get "record_provenance/show"
  resources :audited_activities, only: [:index, :show]

  resources :project_users, except: [:new, :create, :edit]

  resources :projects, except: [:destroy] do
    resources :project_memberships, except: [:edit, :update]
    resources :project_affiliated_records, except: [:edit, :update]
  end

  resources :core_users, except: [:new, :create, :edit]
  resources :cores, except: [:edit, :update, :destroy] do
    resources :core_memberships, except: [:edit, :update]
  end

  resources :records, only: [:index, :show, :new, :create, :destroy]
  resources :repository_users

  get "switch_user/switch_to", as: 'switch_to'
  get "switch_user/destroy", as: 'switch_back'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/check"
  root 'sessions#new'

  

end

app/views/layouts/_authentication.html.erb
<div id="authentication">
<% if current_user %>
  <p>
    Authenticated as <b><%= shib_user.name %></b>.
    <%= link_to 'Logout', sessions_destroy_url( target: url_for(params.merge(only_path: false) ) ) %>
  </p>
  <% if puppet %>
    <p>
      Acting as <b><%= puppet.name %></b>.
      <%= link_to 'Switch back', switch_back_url  %>
    </p>
  <% else %>
    <div>
      <%= render 'layouts/switch_user_form' %>
    </div>
    <% end %>
<% else %>
  <% if @redirect_target.nil? %>
  <%= link_to 'login', Rails.application.config.shibboleth_login_url, target: url_for(params.merge(only_path: false)) %>
  <% else %>
  <%= link_to 'login', Rails.application.config.shibboleth_login_url+'?target='+@redirect_target %>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<div id="navigation">
  <%= link_to 'home', root_url %>
  <%= link_to 'audited activities', audited_activities_path if can? :index, AuditedActivity %>
  <%= link_to 'projects', projects_url if can? :index, Project %>
  <%= link_to 'project users', project_users_url if can? :index, ProjectUser %>
  <%= link_to 'cores', cores_url if can? :index, Core %>
  <%= link_to 'core users', core_users_url if can? :index, CoreUser %>
  <%= link_to 'users', repository_users_url if can? :index, RepositoryUser %>
  <%= link_to 'records', records_url if can? :index, Record %>
</div>

app/views/layouts/_switch_user_form.html.erb
<%= 
form_tag(switch_to_path, method: :get) do
  select_tag(:id, options_from_collection_for_select(switch_to_users, :id, :name, @user.nil? ? nil :@user.id)) +
  submit_tag('switch user')
end
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rads</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag 'body', :class => (puppet ? 'switched_user' : nil) do %>

<% if shib_user %>
<%= render '/layouts/navigation' %>
<% end %>
<%= render 'layouts/authentication' %>
<%= content_tag(:p, alert, id: :notice) if alert %>
<%= content_tag(:p, notice, id: :notice) if notice %>
<%= yield %>

<% end %>
</html>